package com.saleit.constants;

public interface SaleitSuccessConstatnts {
	String SUCC_ADDITEMTOCART_001="SUCC_ADDITEMTOCART_001";
	String SUCC_ADDITEMTOCART_002="SUCC_ADDITEMTOCART_002";
	String SUCC_ADDITEMTOCART_003="SUCC_ADDITEMTOCART_003";
	
	
	
	
	String SUCC_ORDERSERVICE_001= "SUCC_ORDERSERVICET_001";
	String SUCC_ORDERSERVICE_002= "SUCC_ORDERSERVICET_002";
	String SUCC_ORDERSERVICE_003= "SUCC_ORDERSERVICET_003";
}
