package com.saleit.constants;

public interface SaleitSuccessConstatnts {
	String SUCC_ADDITEMTOCART_001="SUCC_ADDITEMTOCART_001";
	String SUCC_ADDITEMTOCART_002="SUCC_ADDITEMTOCART_002";
	String SUCC_ADDITEMTOCART_003="SUCC_ADDITEMTOCART_003";
	String SUCC_ADDITEMTOCART_004="SUCC_ADDITEMTOCART_004";
}
