package com.saleit.constants;

public interface SaleitErrorConstatns {
	
String ERROR_ADDITEMTOCART_001="ERROR_ADDITEMTOCART_001";
String ERROR_ADDITEMTOCART_002="ERROR_ADDITEMTOCART_002";
String ERROR_ADDITEMTOCART_003="ERROR_ADDITEMTOCART_003";
String ERROR_ADDITEMTOCART_004="ERROR_ADDITEMTOCART_004";
String ERROR_ADDITEMTOCART_005="ERROR_ADDITEMTOCART_005";
String ERROR_ADDITEMTOCART_006="ERROR_ADDITEMTOCART_006";
String ERROR_ADDITEMTOCART_007="ERROR_ADDITEMTOCART_007";
String ERROR_ADDITEMTOCART_008="ERROR_ADDITEMTOCART_008";
String ERROR_ADDITEMTOCART_009="ERROR_ADDITEMTOCART_009";
String ERROR_ADDITEMTOCART_010="ERROR_ADDITEMTOCART_010";
String ERROR_ADDITEMTOCART_011="ERROR_ADDITEMTOCART_011";



String ERROR_ORDERSERVICE_001="ERROR_ORDERSERVICE_001";
String ERROR_ORDERSERVICE_002="ERROR_ORDERSERVICE_002";
String ERROR_ORDERSERVICE_003="ERROR_ORDERSERVICE_003";
String ERROR_ORDERSERVICE_004 = "ERROR_ORDERSERVICE_004";
String ERROR_ORDERSERVICE_005= "ERROR_ORDERSERVICE_005";


String ERROR_USERSERVICES_001= "ERROR_USERSERVICES_001";
String ERROR_USERSERVICES_002= "ERROR_USERSERVICES_002";
String ERROR_USERSERVICES_003= "ERROR_USERSERVICES_003";
String ERROR_USERSERVICES_004= "ERROR_USERSERVICES_004";
String ERROR_USERSERVICES_005= "ERROR_USERSERVICES_005";
String ERROR_USERSERVICES_006= "ERROR_USERSERVICES_006";
}
