package com.saleit.constants;

public interface SaleitErrorConstatns {
	
String ERROR_ADDITEMTOCART_001="ERROR_ADDITEMTOCART_001";
String ERROR_ADDITEMTOCART_002="ERROR_ADDITEMTOCART_002";
String ERROR_ADDITEMTOCART_003="ERROR_ADDITEMTOCART_003";
String ERROR_ADDITEMTOCART_004="ERROR_ADDITEMTOCART_004";
String ERROR_ADDITEMTOCART_005="ERROR_ADDITEMTOCART_005";
String ERROR_ADDITEMTOCART_006="ERROR_ADDITEMTOCART_006";
String ERROR_ADDITEMTOCART_007="ERROR_ADDITEMTOCART_007";
String ERROR_ADDITEMTOCART_008="ERROR_ADDITEMTOCART_008";
}
